argocd-apps:
  applications:
    - name: operador
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: torrecontrol
      sources:
        - repoURL: 'https://github.com/keycloak/keycloak-k8s-resources'
          targetRevision: 26.0.6
          path: kubernetes
          directory:
            recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true     
